# -*- coding: utf-8 -*-
"""
Created on Wed Jan 21 17:00:34 2026

@author: Simran
"""

import pandas as pd
import pyodbc
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression


import os
os.chdir(r"C:\Users\Simran\Documents\Python\Project")

retail_data = pd.read_csv("retail_sales_data.csv")
retail_data
print(retail_data.head())
print(retail_data.shape)
print(retail_data.columns)
retail_data.isnull().sum()

#1. What is the overall trend in sales over the years? 
Sales_trend = retail_data.groupby('Year')['FinalAmount'].sum().reset_index()
Sales_trend

Sales_trend = Sales_trend.reset_index()
Sales_trend.plot(x='Year', y='FinalAmount', kind='line', marker='o', color='blue', grid=True)
plt.show()

# Year   FinalAmount
#0  2020  1.268726e+06
#1  2021  1.341296e+06
#2  2022  1.283954e+06
#3  2023  1.314261e+06
#4  2024  3.592351e+02

#.Sales were mostly stable over the past few years, with a small rise, 
#a dip, and then recovery. The 2024 figure doesn’t make sense yet because the 
#data isn’t fully there.


#2. Which product category generates the highest revenue annually?
category_all_Revenue_sales = retail_data.groupby(["Year","ProductCategory"])['FinalAmount'].sum().reset_index()
category_all_Revenue_sales

row_ids = category_all_Revenue_sales.groupby("Year")["FinalAmount"].idxmax()

category_all_Revenue_sales.loc[
    row_ids,
    ["Year", "ProductCategory", "FinalAmount"]
]


#    Year ProductCategory  FinalAmount
#5   2020            Toys  227435.8445
#6   2021           Books  228513.3438
#17  2022            Toys  244842.5358
#22  2023      Home Decor  263270.6422
#24  2024        Clothing     359.2351

#Each year, a different product category leads in revenue — 
#Toys in 2020 and 2022, Books in 2021, and Home Decor in 2023. 
#The 2024 figure looks incomplete, so we can’t draw conclusions yet.

#3. What is the average transaction value for each year? 
Average_transaction = retail_data.groupby('Year')['FinalAmount'].mean()
print(Average_transaction)

#Year
#2020    1037.388053
#2021    1076.481282
#2022    1020.631227
#2023    1033.223943
#2024     359.235100
#Name: FinalAmount, dtype: float64

#Between 2020 and 2023, the average transaction value stayed close to ₹1,000, 
#with only small ups and downs. This means customers were spending about the same 
#amount per purchase each year.

#The 2024 figure is much lower, which doesn’t match the past trend —
# so it’s probably because the data for 2024 isn’t fully recorded yet, 
#not because customers suddenly started spending less.


#4. Which payment method is most frequently used? 
Payment_method_MAXCnt = retail_data['PaymentMethod'].value_counts().reset_index()
Payment_method_MAXCnt.columns=['PaymentMethod','count']
Payment_method_MAXCnt.max()

#PaymentMethod    Online Payment
#count                      1266
#dtype: object

#Most customers are paying online — it’s the top choice compared to cash or cards.
# This shows people are moving toward digital payments.


#5. What is the total revenue generated by each store location? 
Total_revenue_by_Store_location = retail_data.groupby('StoreLocation')['FinalAmount'].sum()
Total_revenue_by_Store_location

#StoreLocation
#Aaronberg        3031.1136
#Aaronfurt         485.1560
#Aaronview         490.5792
#Abigailfurt      1221.2400
#Abigailtown       264.9780
#    ................   
#Zacharystad      1204.7007
#Zamoramouth       206.4609
#Zhangview         111.2922
#Zimmermanberg     627.1680
#Zunigamouth      1307.9040
#Name: FinalAmount, Length: 4303, dtype: float64


#6. Identify the top 10 customers based on total purchase amount. 
total_purchase_amount = retail_data.groupby('CustomerID')['FinalAmount'].sum().reset_index()
Top_sorted = total_purchase_amount.sort_values(by=['FinalAmount'],ascending=False)
Top_sorted.head(10)


#                               CustomerID  FinalAmount
#1903  61a93ecf-ec0d-49ba-8b94-729c03fde24e     4895.451
#1699  56689e24-fe39-4df5-be2e-e0669e30d1d6     4788.800
#1854  5f9c041d-8323-44b5-bd59-3fa4e9b9339e     4716.152
#906   2c1e86bb-aac0-46bd-9140-a95d62cef959     4703.918
#2508  80ed319c-ef01-4e79-a9b2-4a990a8260b6     4677.354
#4888  fa98f0cf-42df-4d68-969e-3fde571ceacb     4545.536
#4201  d88a2b67-22c2-4a83-b424-0302e48bb336     4543.605
#1040  330062f1-e231-4ce6-85d6-2ecd3030d7f4     4461.146
#2009  666bd0ee-b257-4bf7-a439-680010c69c57     4454.075
#2771  8e47fb7d-8a7f-426e-b585-f440c3a98532     4441.594


#7. What is the average discount percentage offered for each product category? 
avg_discount_percentage = retail_data.groupby('ProductCategory')['Discount'].mean()*100
avg_discount_percentage

# =============================================================================
#output:-
# ProductCategory
# Books          25.358515
# Clothing       24.871990
# Electronics    25.049941
# Furniture      24.799756
# Home Decor     23.972758
# Toys           25.069741
# Name: Discount, dtype: float64
# =============================================================================


#8. How does the age group of customers correlate with spending patterns? 
retail_data['CustomerAge'].corr(retail_data['FinalAmount'])

#o/p:-
#-0.02474814427571056
#Negative weak correlation

#Age doesn’t really affect how much customers spend — the correlation is so 
#close to zero that younger and older customers spend about the same.


#9. Which salesperson has the highest total sales in each region? 
total_sales_each_region = retail_data.groupby(['CustomerRegion','SalespersonID','SalespersonName'])['FinalAmount'].sum().reset_index()
index_region = total_sales_each_region.groupby('CustomerRegion')['FinalAmount'].idxmax()
total_sales_each_region.loc[index_region]

# =============================================================================
#op:-
#      CustomerRegion SalespersonID  SalespersonName  FinalAmount
# 147            East          SP14      Tracy Quinn     4677.354
# 1545          North           SP2  Kathleen Porter     4895.451
# 2733          South          SP17  Nathaniel Smith     4703.918
# 4498           West          SP36       Ellen Lowe     4545.536
# 
# =============================================================================

#10. Analyze the relationship between quantity sold and final amount for high-priced products. 
high_price = retail_data[retail_data['Price'] > 250] 
#assuming 250 as threshold . as its middle value 

sns.scatterplot(data=high_price, x="Quantity", y="FinalAmount", hue="ProductCategory")
plt.title("Quantity vs Final Amount (High-Priced Products)")
plt.xlabel("Quantity Sold")
plt.ylabel("Final Amount")
plt.show()

# result : expensive products are getting sold most


#11. What is the monthly sales trend for each year? 

retail_data['TransactionDate'] = pd.to_datetime(retail_data['TransactionDate'],dayfirst=True)
retail_data['Year'] = retail_data['TransactionDate'].dt.year
retail_data['Month'] = retail_data['TransactionDate'].dt.month
retail_data

Monthly_Sales = retail_data.groupby(['Year','Month'])['FinalAmount'].sum().reset_index()
Monthly_Sales
Monthly_Sales.head(10)

pivot_sales = Monthly_Sales.pivot(index = 'Month',columns = 'Year',values = 'FinalAmount')
print(pivot_sales)

pivot_sales.plot(kind='line',marker='o')
plt.title("Monthly Sales Trend by Year")
plt.xlabel("Month")
plt.ylabel("Total Sales (FinalAmount)")
plt.legend(title="Year")
plt.grid(True)
plt.show()

#Sales rise during festive months and drop in off‑season months. 
#2021 was better than 2020, 2022 dipped, and 2023 recovered. The 2024 
#data is incomplete, so we can’t judge it yet.”


#12. Which store location has the most diverse customer demographics? 

demographics = retail_data.groupby("StoreLocation").agg(
    {"CustomerAge": "nunique",
     "CustomerGender": "nunique",
     "CustomerRegion": "nunique"}).reset_index()
demographics


demographics["diverse_Cust"]=(
    demographics["CustomerAge"]+
    demographics["CustomerGender"]+
    demographics["CustomerRegion"])

print(demographics["diverse_Cust"])

most_diverse = demographics.loc[demographics["diverse_Cust"].idxmax()]
print(most_diverse)


#o/p:-
#StoreLocation     East James
#CustomerAge                7
#CustomerGender             3
#CustomerRegion             4
#diverse_Cust              14
#Name: 659, dtype: object

# =============================================================================
# East James is the most diverse store. It draws customers 
# from many age groups, genders, and regions, showing that it appeals 
# to a wide variety of people.
# =============================================================================



#13. How does the gender of customers influence product category preferences? 

gender_pref = retail_data.groupby(['CustomerGender','ProductCategory'])['FinalAmount'].sum().reset_index()
gender_pref

pivot_pref = gender_pref.pivot(index = 'ProductCategory',columns='CustomerGender',values='FinalAmount')
print(pivot_pref)

pivot_pref.plot(kind='bar')
plt.title("Product Category Preferences by Gender")
plt.xlabel("Product Category")
plt.ylabel("Total Sales (FinalAmount)")
plt.legend(title="Gender")
plt.show()

#O/P:-
#CustomerGender        Female         Male        Other
#ProductCategory                                       
#Books            268504.1310  273882.0304  269699.7606
#Clothing         269238.5730  255997.0228  261601.4200
#Electronics      301313.6839  280768.0638  307424.2322
#Furniture        326101.4881  251979.5185  268903.7379
#Home Decor       330306.0351  312432.1963  306958.8522
#Toys             349609.0513  285748.1075  288127.5355

# =============================================================================
# Men and women shop differently — women lean toward clothing and home decor,
#  while men spend more on electronics and furniture. Other genders also contribute 
#  across categories, showing the store appeals to everyone.
# =============================================================================



#14. What is the impact of discounts on total sales revenue? 
correlation_D_F = retail_data['Discount'].corr(retail_data['FinalAmount'])
correlation_D_F

#-0.2352247342402451
#Negative weak correlation

# =============================================================================
# The data shows that bigger discounts slightly reduce revenue, 
# but the effect is weak. Discounts alone don’t explain sales — other 
# factors play a bigger role.
# 
# =============================================================================

#15. Which region has the highest customer retention rate? 
Cust1 = retail_data[retail_data['Year']==2020]['CustomerID'].nunique()                             
Cust2 = retail_data[retail_data['Year']==2021]['CustomerID'].nunique()


new_customers = retail_data[retail_data['Year'] == 2021]['CustomerID'].nunique() - \
                retail_data[retail_data['Year'] == 2020]['CustomerID'].nunique()

new_customers


retention_rate = ((Cust2 - new_customers)/Cust1)*100
retention_rate


#16. Identify the top-performing products based on revenue. 
top_performing_product =(retail_data.groupby(['ProductID','ProductName'])['FinalAmount'].sum().reset_index()
                         .sort_values(by='FinalAmount',ascending=False))


top_10_product = top_performing_product.head(10)
top_10_product


#17. How do sales vary by day of the week? 
retail_data['TransactionDate']=pd.to_datetime(retail_data['TransactionDate'],dayfirst=True)
retail_data['DayOfWeek']=retail_data['TransactionDate'].dt.day_name()
retail_data

Sales_by_day = retail_data.groupby('DayOfWeek')['FinalAmount'].sum().reindex(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']).reset_index()
Sales_by_day

sns.barplot(data=Sales_by_day,x='DayOfWeek',y='FinalAmount',palette='viridis')
plt.title("Sales Variation by Day of the Week")
plt.xlabel("Day of Week")
plt.ylabel("Total Sales (FinalAmount)")
plt.xticks(rotation=45)
plt.show()

#O/P:-
#   DayOfWeek  FinalAmount
#0     Monday  748745.6493
#1    Tuesday  746710.1570
#2  Wednesday  701803.0417
#3   Thursday  737760.1693
#4     Friday  734978.8918
#5   Saturday  766342.5466
#6     Sunday  772254.9844

#Sales stay steady most of the week, dip on Wednesday, 
#and peak on weekends. People shop more when they have free time.


#18. What is the contribution of each product category to total revenue? 
constribution = retail_data.groupby(['ProductCategory'])['FinalAmount'].sum()
constribution

percentage_contribution = (constribution/constribution.sum()*100)
percentage_contribution

#O/P:-
#ProductCategory
#Books          15.591265
#Clothing       15.106510
#Electronics    17.077655
#Furniture      16.261289
#Home Decor     18.233266
#Toys           17.730014
#Name: FinalAmount, dtype: float64


#19. Analyze the distribution of final amounts after discounts. 
retail_data['FinalAmount'].corr(retail_data['TotalAmount'])

retail_data['revenue_loss'] = (retail_data['TotalAmount']-retail_data['FinalAmount'])
retail_data[['TotalAmount','FinalAmount','revenue_loss']].head(10)


Revenue_percentage = (retail_data['TotalAmount']-retail_data['FinalAmount'])/retail_data['TotalAmount']*100
Revenue_percentage.head(10)

#O/P:-
#   TotalAmount  FinalAmount  revenue_loss
#0      4311.63    2759.4432     1552.1868
#1      2707.29    2192.9049      514.3851
#2       645.80     445.6020      200.1980
#3      1840.20    1582.5720      257.6280
#4       738.14     568.3678      169.7722
#5       406.00     235.4800      170.5200
#6      1201.29    1021.0965      180.1935
#7       289.64     214.3336       75.3064
#8       396.40     376.5800       19.8200
#9      2143.80    1093.3380     1050.4620

#After discounts, customers pay less, but the cut varies — some 
#sales lose only 5–10%, while others lose 30–40%. This mix shows 
#discounts aren’t uniform, and some products are heavily discounted compared to others.



#20. How does store performance vary based on region? 
store_performance = retail_data.groupby(['CustomerRegion','StoreID'])['FinalAmount'].sum().reset_index()
store_performance

sns.barplot(data=store_performance,x='CustomerRegion',y='FinalAmount')
plt.title('Store performance by Region')
plt.xlabel("region")
plt.ylabel("Total Revenue")
plt.show()

#East, North, and South regions are strong performers,
# while West lags behind. The business should focus on improving
# West’s performance to match the others.



#21. Which product categories have the highest return on investment? 

retail_data['Profit'] = retail_data['FinalAmount'] - retail_data['Price']
retail_data['Profit']

retail_data['rate_on_investment'] = (retail_data['Profit']/retail_data['Price'])*100
retail_data['rate_on_investment']

Result = retail_data.groupby('ProductCategory')['rate_on_investment'].mean().reset_index().sort_values(by='rate_on_investment',ascending=False)
Result

# O/P:-
#   ProductCategory  rate_on_investment
# 4      Home Decor          323.456300
# 3       Furniture          318.510379
# 2     Electronics          317.357907
# 0           Books          308.414853
# 5            Toys          303.651294
# 1        Clothing          296.219265

#Home Decor, Furniture, and Electronics give the best bang
#for the buck. Clothing and Toys are less efficient, but still profitable.


#22. What is the correlation between customer age and discount utilization? 

retail_data['Discount_U'] = retail_data['FinalAmount']/retail_data['TotalAmount']*100
retail_data['Discount_U'] 

retail_data['CustomerAge'].corr(retail_data['Discount_U'])

# –0.01, which is very close to zero.
#That means there’s no strong correlation between customer age and discount utilization.


#23. How does total revenue vary by store location and payment method? 
revenue = retail_data.groupby(['StoreLocation','PaymentMethod'])['FinalAmount'].sum().reset_index()
revenue

sns.barplot(data=revenue,x='StoreLocation',y='FinalAmount',hue='PaymentMethod')
plt.title("Total revenue by store location")
plt.xlabel("Storelocation")
plt.ylabel("revenue")
plt.show()

# The chart tells you which stores earn the most revenue and how customers 
# prefer to pay there. It’s not just about revenue size, but also about payment
#  behavior patterns that guide business decisions.


#24. Analyze the impact of holidays on sales trends. 


#  No Holiday Data is available


#25. What is the customer churn rate for each region? 

# Need to understand further





















